[2021-06-15 21:50:30,105] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_homer_simpson.tercera_parte 2021-05-20T11:00:00+00:00 [queued]>
[2021-06-15 21:50:30,166] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_homer_simpson.tercera_parte 2021-05-20T11:00:00+00:00 [queued]>
[2021-06-15 21:50:30,168] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 21:50:30,171] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-15 21:50:30,172] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 21:50:30,199] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): tercera_parte> on 2021-05-20T11:00:00+00:00
[2021-06-15 21:50:30,210] {standard_task_runner.py:53} INFO - Started process 851 to run task
[2021-06-15 21:50:31,002] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_homer_simpson.tercera_parte 2021-05-20T11:00:00+00:00 [running]> 651693a3c8b0
[2021-06-15 21:50:31,055] {taskinstance.py:1145} ERROR - 'int' object is not iterable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_homer_simpson.py", line 20, in relleno
    for i in 150:
TypeError: 'int' object is not iterable
[2021-06-15 21:50:31,076] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dag_homer_simpson, task_id=tercera_parte, execution_date=20210520T110000, start_date=20210615T215030, end_date=20210615T215031
[2021-06-15 21:50:40,028] {logging_mixin.py:112} INFO - [2021-06-15 21:50:40,028] {local_task_job.py:103} INFO - Task exited with return code 1
