[2021-06-22 19:04:11,875] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_python 2021-06-22T19:03:42.662810+00:00 [queued]>
[2021-06-22 19:04:11,954] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_python 2021-06-22T19:03:42.662810+00:00 [queued]>
[2021-06-22 19:04:11,956] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:04:11,961] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-22 19:04:11,962] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:04:12,004] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-06-22T19:03:42.662810+00:00
[2021-06-22 19:04:12,009] {standard_task_runner.py:53} INFO - Started process 597 to run task
[2021-06-22 19:04:12,798] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagPrueba_xcom.prueba_python 2021-06-22T19:03:42.662810+00:00 [running]> 651693a3c8b0
[2021-06-22 19:04:12,852] {logging_mixin.py:112} INFO - hello
[2021-06-22 19:04:12,853] {logging_mixin.py:112} INFO - world
[2021-06-22 19:04:12,855] {python_operator.py:114} INFO - Done. Returned value was: Retornando Datos
[2021-06-22 19:04:12,933] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dagPrueba_xcom, task_id=prueba_python, execution_date=20210622T190342, start_date=20210622T190411, end_date=20210622T190412
[2021-06-22 19:04:21,763] {logging_mixin.py:112} INFO - [2021-06-22 19:04:21,762] {local_task_job.py:103} INFO - Task exited with return code 0
