[2021-06-23 18:41:04,667] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_pull 2021-03-15T15:00:00+00:00 [queued]>
[2021-06-23 18:41:04,740] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_pull 2021-03-15T15:00:00+00:00 [queued]>
[2021-06-23 18:41:04,743] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 18:41:04,747] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-23 18:41:04,749] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 18:41:04,861] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_pull> on 2021-03-15T15:00:00+00:00
[2021-06-23 18:41:04,883] {standard_task_runner.py:53} INFO - Started process 2397 to run task
[2021-06-23 18:41:06,219] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_prueba_macros.prueba_pull 2021-03-15T15:00:00+00:00 [running]> 651693a3c8b0
[2021-06-23 18:41:06,338] {logging_mixin.py:112} INFO - None
[2021-06-23 18:41:06,340] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-23 18:41:06,392] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_prueba_macros, task_id=prueba_pull, execution_date=20210315T150000, start_date=20210623T184104, end_date=20210623T184106
[2021-06-23 18:41:14,530] {logging_mixin.py:112} INFO - [2021-06-23 18:41:14,529] {local_task_job.py:103} INFO - Task exited with return code 0
