[2021-06-15 21:50:28,736] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_homer_simpson.tercera_parte 2021-06-15T21:49:37.510923+00:00 [queued]>
[2021-06-15 21:50:28,837] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_homer_simpson.tercera_parte 2021-06-15T21:49:37.510923+00:00 [queued]>
[2021-06-15 21:50:28,839] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 21:50:28,842] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-15 21:50:28,843] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 21:50:28,874] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): tercera_parte> on 2021-06-15T21:49:37.510923+00:00
[2021-06-15 21:50:28,893] {standard_task_runner.py:53} INFO - Started process 838 to run task
[2021-06-15 21:50:29,568] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_homer_simpson.tercera_parte 2021-06-15T21:49:37.510923+00:00 [running]> 651693a3c8b0
[2021-06-15 21:50:29,663] {taskinstance.py:1145} ERROR - 'int' object is not iterable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_homer_simpson.py", line 20, in relleno
    for i in 150:
TypeError: 'int' object is not iterable
[2021-06-15 21:50:29,679] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dag_homer_simpson, task_id=tercera_parte, execution_date=20210615T214937, start_date=20210615T215028, end_date=20210615T215029
[2021-06-15 21:50:38,595] {logging_mixin.py:112} INFO - [2021-06-15 21:50:38,595] {local_task_job.py:103} INFO - Task exited with return code 1
