[2021-06-22 19:04:25,891] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:03:42.662810+00:00 [queued]>
[2021-06-22 19:04:25,929] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:03:42.662810+00:00 [queued]>
[2021-06-22 19:04:25,931] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:04:25,934] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-22 19:04:25,936] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:04:25,970] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_pull> on 2021-06-22T19:03:42.662810+00:00
[2021-06-22 19:04:25,981] {standard_task_runner.py:53} INFO - Started process 737 to run task
[2021-06-22 19:04:26,699] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:03:42.662810+00:00 [running]> 651693a3c8b0
[2021-06-22 19:04:26,750] {taskinstance.py:1145} ERROR - 'task_instance'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_hello_xcom.py", line 20, in prueba_pull
    ti = context['task_instance']
KeyError: 'task_instance'
[2021-06-22 19:04:26,767] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dagPrueba_xcom, task_id=prueba_pull, execution_date=20210622T190342, start_date=20210622T190425, end_date=20210622T190426
[2021-06-22 19:04:35,848] {logging_mixin.py:112} INFO - [2021-06-22 19:04:35,847] {local_task_job.py:103} INFO - Task exited with return code 1
