[2021-06-22 16:01:01,477] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_python 2021-05-29T11:00:00+00:00 [queued]>
[2021-06-22 16:01:01,524] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_python 2021-05-29T11:00:00+00:00 [queued]>
[2021-06-22 16:01:01,527] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 16:01:01,529] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-22 16:01:01,531] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 16:01:01,554] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-05-29T11:00:00+00:00
[2021-06-22 16:01:01,561] {standard_task_runner.py:53} INFO - Started process 547 to run task
[2021-06-22 16:01:01,864] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagPrueba_xcom.prueba_python 2021-05-29T11:00:00+00:00 [running]> 651693a3c8b0
[2021-06-22 16:01:02,025] {logging_mixin.py:112} INFO - hello
[2021-06-22 16:01:02,039] {logging_mixin.py:112} INFO - world
[2021-06-22 16:01:02,050] {python_operator.py:114} INFO - Done. Returned value was: Retornando Datos
[2021-06-22 16:01:02,360] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dagPrueba_xcom, task_id=prueba_python, execution_date=20210529T110000, start_date=20210622T160101, end_date=20210622T160102
[2021-06-22 16:01:11,414] {logging_mixin.py:112} INFO - [2021-06-22 16:01:11,412] {local_task_job.py:103} INFO - Task exited with return code 0
