[2021-06-23 18:41:05,856] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_python 2021-03-15T15:00:00+00:00 [queued]>
[2021-06-23 18:41:05,961] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_python 2021-03-15T15:00:00+00:00 [queued]>
[2021-06-23 18:41:05,963] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 18:41:05,965] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-23 18:41:05,966] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 18:41:06,020] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-03-15T15:00:00+00:00
[2021-06-23 18:41:06,038] {standard_task_runner.py:53} INFO - Started process 2400 to run task
[2021-06-23 18:41:06,974] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_prueba_macros.prueba_python 2021-03-15T15:00:00+00:00 [running]> 651693a3c8b0
[2021-06-23 18:41:07,183] {logging_mixin.py:112} INFO - hello
[2021-06-23 18:41:07,185] {logging_mixin.py:112} INFO - world
[2021-06-23 18:41:07,290] {python_operator.py:114} INFO - Done. Returned value was: Retornando Datos
[2021-06-23 18:41:07,548] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_prueba_macros, task_id=prueba_python, execution_date=20210315T150000, start_date=20210623T184105, end_date=20210623T184107
[2021-06-23 18:41:15,532] {logging_mixin.py:112} INFO - [2021-06-23 18:41:15,529] {local_task_job.py:103} INFO - Task exited with return code 0
