[2021-06-23 19:04:59,049] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_pull 2021-06-23T19:04:08.884072+00:00 [queued]>
[2021-06-23 19:04:59,097] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_pull 2021-06-23T19:04:08.884072+00:00 [queued]>
[2021-06-23 19:04:59,098] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 19:04:59,099] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-23 19:04:59,100] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 19:04:59,130] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_pull> on 2021-06-23T19:04:08.884072+00:00
[2021-06-23 19:04:59,135] {standard_task_runner.py:53} INFO - Started process 3390 to run task
[2021-06-23 19:04:59,615] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_prueba_macros.prueba_pull 2021-06-23T19:04:08.884072+00:00 [running]> 651693a3c8b0
[2021-06-23 19:04:59,910] {logging_mixin.py:112} INFO - Retornando Datos
[2021-06-23 19:04:59,911] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-23 19:04:59,938] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_prueba_macros, task_id=prueba_pull, execution_date=20210623T190408, start_date=20210623T190459, end_date=20210623T190459
[2021-06-23 19:05:08,964] {logging_mixin.py:112} INFO - [2021-06-23 19:05:08,964] {local_task_job.py:103} INFO - Task exited with return code 0
