[2021-06-22 19:19:22,954] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:18:42.668157+00:00 [queued]>
[2021-06-22 19:19:22,987] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:18:42.668157+00:00 [queued]>
[2021-06-22 19:19:22,992] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:19:22,994] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-22 19:19:22,995] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:19:23,020] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_pull> on 2021-06-22T19:18:42.668157+00:00
[2021-06-22 19:19:23,024] {standard_task_runner.py:53} INFO - Started process 3186 to run task
[2021-06-22 19:19:23,235] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:18:42.668157+00:00 [running]> 651693a3c8b0
[2021-06-22 19:19:23,379] {logging_mixin.py:112} INFO - Retornando Datos
[2021-06-22 19:19:23,381] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-22 19:19:23,423] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dagPrueba_xcom, task_id=prueba_pull, execution_date=20210622T191842, start_date=20210622T191922, end_date=20210622T191923
[2021-06-22 19:19:32,909] {logging_mixin.py:112} INFO - [2021-06-22 19:19:32,908] {local_task_job.py:103} INFO - Task exited with return code 0
