[2021-06-23 19:05:15,454] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_python 2021-06-23T19:04:45.477954+00:00 [queued]>
[2021-06-23 19:05:15,510] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba_macros.prueba_python 2021-06-23T19:04:45.477954+00:00 [queued]>
[2021-06-23 19:05:15,512] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 19:05:15,514] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-23 19:05:15,515] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-23 19:05:15,538] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-06-23T19:04:45.477954+00:00
[2021-06-23 19:05:15,546] {standard_task_runner.py:53} INFO - Started process 3561 to run task
[2021-06-23 19:05:16,734] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_prueba_macros.prueba_python 2021-06-23T19:04:45.477954+00:00 [running]> 651693a3c8b0
[2021-06-23 19:05:16,935] {logging_mixin.py:112} INFO - hello
[2021-06-23 19:05:16,966] {logging_mixin.py:112} INFO - world
[2021-06-23 19:05:17,127] {python_operator.py:114} INFO - Done. Returned value was: Retornando Datos
[2021-06-23 19:05:17,238] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_prueba_macros, task_id=prueba_python, execution_date=20210623T190445, start_date=20210623T190515, end_date=20210623T190517
[2021-06-23 19:05:25,401] {logging_mixin.py:112} INFO - [2021-06-23 19:05:25,401] {local_task_job.py:103} INFO - Task exited with return code 0
